asyncapi/asyncapi-react

library/package.json, package.json
- Update scripts in `core` and `library` package.jsons,
- Update authors in package.jsons
=> Update scripts and authors

library/package.json, package-lock.json, playground/package-lock.json, playground/package.json, playground/public/index.css, playground/public/index.html, playground/src/index.tsx
- Add scripts for `gh-pages` branch in `package.json`
=> Add scripts for gh-pages

.gitignore, README.md, library/package-lock.json, library/package.json, library/src/components/Code.tsx, library/src/components/styled.ts, library/src/containers/AsyncApi/AsyncApi.tsx, library/src/theme/default.ts, library/src/theme/styled-components.ts, library/src/theme/theme.ts, library/tsconfig.json, package-lock.json, package.json, playground/config-overrides.js, playground/package-lock.json, playground/package.json, playground/src/App.tsx, playground/src/common/defaultTheme.ts
- Update `Readme.md` with new name of package in npm,
- Update `package.json` of library,
- Remove mocks, unnecessary packages and old content.
Resolves #13
=> Publish first version on npm

README.md
- Add sandbox example to README
=> Add sandbox example to README

library/package.json
- Downgrade required peer dependency version
=> Downgrade required peer dependency version

.gitignore, README.md, lerna.json, library/package-lock.json, package.json, playground/package-lock.json
- Integrate Lerna changelog
https://github.com/asyncapi/asyncapi-react/issues/22
=> Integrate Lerna changelog

library/package-lock.json, library/package.json, playground/package-lock.json, playground/package.json
- Bump library version to 0.1.1 and documentation version to 0.1.3
=> Bump library version to 0.1.1 and documentation version to 0.1.3

library/package-lock.json, library/package.json, playground/package-lock.json, playground/package.json
- Bump library and documentation version to 0.2.0
=> Bump library and documentation version to 0.2.0

README.md
- Update sandbox example to match 0.2.0 release
=> Update sandbox example to match 0.2.0 release

library/package-lock.json, library/package.json
- Update asyncapi-parser` to support 2.0.0.
=> Update parser to support 2.0.0

library/package-lock.json, library/package.json
=> Upgrade component to 0.3.1

README.md
- Add new link to sandbox that uses AsyncAPI 0.3.1
=> Add new link to sandbox that uses AsyncAPI 0.3.1

.gitignore, library/package-lock.json, library/package.json, library/src/components/Toggle.tsx
Updates to latest asyncai-parser version 0.16.2
=> feat: update asyncapi-parser to version 0.16.2

.github/workflows/release.yml, .github/workflows/simple-pr-validation.yml, library/src/containers/AsyncApi/AsyncApi.tsx, library/src/helpers/__tests__/parser.test.ts, library/src/helpers/parser.ts, library/src/react-app-env.d.ts, playground/package-lock.json, playground/package.json
- updating refs to new parser in tests because now they fail and block release
- added new GH workflow for simple PR validation to prevent above in future
- added one step to release workflow to bump playground dependency and have it pushed automatically to repo
=> fix: updating parser deps in tests and adding simple PR validation

library/src/containers/Schemas/SchemaProperties.tsx, library/src/styles/fiori.css
Displays enums when they are set. Style was taken from the asyncapi/generator
Resolved #93
=> display enums in component if available

CODEOWNERS
As discussed offline, we (Kyma Team) decided to change the code ownership from the whole Kyma Team to particular persons that are involved in the project. Starting from now, anyone who is working on this project may become its code owner, not only the Kyma team members.
@kazydek @bszwarc @mmitoraj @aerfio @magicmatatjahu @derberg @m00g3n I will wait with the merge for your approvals.
=> Change code ownership to the true owners

playground/package-lock.json, playground/package.json
Fixes `react-scripts` dependency. Version 3.1.1 is not working.
=> fix: Fixes project dependencies

library/src/containers/Schemas/Schema.tsx, library/src/helpers/beautifier.ts, library/src/styles/fiori.css, library/src/types.ts
=> feat: show additional properties are (not) allowed

library/package-lock.json, library/package.json, playground/package-lock.json
- Bump parser to use release candidate with fix for special sec types
=> fix: Bump parser to use release candidate with fix for special sec types

library/package-lock.json, library/package.json, library/src/containers/AsyncApi/AsyncApi.tsx, library/src/react-app-env.d.ts
Registers Avro, RAML DT, and OpenAPI schema parsers.
Fixes #104
=> feat: Add support for Avro, OpenAPI Schemas, RAML Data Types

library/src/containers/Schemas/Schema.tsx, library/src/containers/Schemas/SchemaProperties.tsx, library/src/styles/fiori.css
- Add more property labels: minimum, maximum, exclusiveMinimum, exclusiveMaximum, uniqueItems, minLength, maxLength, minItems, maxItems.
- Render additionalProperties when it's an object.
- Render array items when it's an object.
- Change the location of the "Additional properties are supported" notice to make it clearer on nested objects.
=> feat: Add more property labels and render complex objects

.github/workflows/release.yml, README.md
- Change codesandbox link to working example
- Fix release workflow - split sleep and install deps to separate processes
Fixes https://github.com/asyncapi/asyncapi-react/issues/106
=> chore: change codesandbox example link and fix release workflow

library/package-lock.json, library/package.json, library/src/containers/Schemas/SchemaProperties.tsx
- correct display of minimal value in case it is 0. The current condition could not work as 0 evaluates to undefined
=> fix: correct display of minimal value in case it is 0

.github/workflows/release.yml, README.md, library/package.json, library/semantic-release.js, package-lock.json, package.json, playground/package-lock.json, playground/package.json, web-component/package-lock.json, web-component/package.json, web-component/semantic-release.js, web-component/src/AsyncApiWebComponent.tsx, web-component/src/index.ts, web-component/webpack.config.js
Improve web component to be production ready:
- Update code inside `web-component` folder,
- Update main Readme.md
- Update github workflow for automatically release of web-component
See also https://github.com/asyncapi/asyncapi-react/pull/148
@gexclaude if you would like to, I invite you to check the PR, especially the changes in readme :)
=> feat: add web-component

.github/workflows/release.yml
=> fix: increase release verbosity

.github/workflows/release.yml
- web-component release pipeline logs and release attempt
=> fix: web-component release pipeline logs and release attempt

.github/workflows/release.yml, README.md, library/package-lock.json, library/package.json, playground/package-lock.json, playground/package.json, playground/src/Playground.tsx, playground/src/index.tsx, web-component/package-lock.json, web-component/package.json, web-component/src/AsyncApiWebComponent.tsx
- First release of all packages under the same scope, @asyncapi. Package under @kyma-project will no longer be updated
=> feat: first release of all packages under the same scope

.github/workflows/release.yml, library/package-lock.json, library/package.json, playground/package-lock.json, playground/package.json, web-component/package-lock.json, web-component/package.json
Start using for publish of `web-component` custom github action - stop doing it manually.
=> fix: use custom github action for publish of web-component

library/package-lock.json, library/package.json, playground/package-lock.json, playground/package.json, web-component/package-lock.json, web-component/package.json
As in title: update version of web-component to `0.16.2`
=> fix: update version of web-component

.github/workflows/release.yml, package.json, web-component/package.json
- properly tag web-component on npm
=> fix: properly tag web-component on npm

.github/workflows/release.yml
- release to use latest version of create pr action
=> fix: release to use latest version of create pr action

.github/workflows/release.yml
- properly bump version of web component
=> fix: properly bump version of web component

README.md
- Add simple app for web-component using Angular in codesandbox,
- Update codesandbox for react-component (change `@kyma-project/asyncapi-react` dep to `@asyncapi/react-component`)
=> docs: add codesandbox for web-component (Angular) and update for react-component

CODEOWNERS
As in title: add to codeowners Fran Mendez @fmvilas.
=> chore: add to codeowners Fran Mendez

.github/workflows/if-nodejs-pr-testing.yml, .github/workflows/if-nodejs-release.yml, .github/workflows/if-nodejs-version-bump.yml, .github/workflows/issues-prs-notifications.yml, .github/workflows/release-wc-and-playground.yml, playground/bump-react-comp.sh, web-component/bump-react-comp.sh
- notify about issues and pr being reopened
- better naming of workflows
- added missing bump of webcomponent before publish
- added missing build of playground before push to ghpages
- explicit checkout of master branch for bump action as normally it would checkout specific commit and cause headache
=> ci: improve release pipeline refactor

.github/workflows/if-nodejs-version-bump.yml
**even though there is no change in the code, this PR fixes workflow that cleanups package.json in the entire project and this must be done as it was failing few releases before and we want to have this change reflected vs recent released version**
- explicit checkout of master branch for bump action as normally it would checkout specific commit and cause headache. This is a problem for a PR creation action
=> fix: improve bump workflow to work on master branch

CODEOWNERS
- add bot to codeowners so automerge action respects it
=> chore: add bot to codeowners so automerge action respects it

CODEOWNERS
- learned from https://github.com/Khan/wonder-blocks/blob/master/CODEOWNERS#L1 a proper name of the bot
=> chore: set proper bot name in codeowners

library/src/containers/Messages/Messages.tsx, library/src/containers/Messages/Payload.tsx
As in title: make fallback for inferred names.
=> fix: make fallback for inferred names

library/src/components/Href.tsx, library/src/components/Markdown.tsx, library/src/containers/AsyncApi/AsyncApi.tsx, library/src/containers/Info/Contact.tsx, library/src/containers/Info/License.tsx, library/src/containers/Info/NewInfo.tsx, playground/public/index.html
This PR brings React component's playground appearance closer to [playground.asyncapi.io](https://playground.asyncapi.io)'s.
Unification process is in progress, CSS styles will be polished further.
=> refactor: rewritten Info component

.github/workflows/bump.yaml, library/package.json, package.json
Add `bump` workflow as suggested in https://github.com/asyncapi/html-template/pull/166#pullrequestreview-639562437
Part of https://github.com/asyncapi/shape-up-process/issues/83
=> ci: add bump workflow

.github/workflows/release-wc-and-playground.yml
Like in title. Publish playground from `next` branch.
=> ci: publish playground from next branch

library/package-lock.json, library/package.json, library/src/containers/Messages/MessageExample.tsx, library/src/helpers/__tests__/message.test.ts, library/src/helpers/message.ts, library/src/helpers/schema.ts, library/src/helpers/server.ts, library/src/types.ts, playground/package-lock.json, web-component/package-lock.json
Support for `2.1.0` version of spec.
Added stuff:
- humanize new security schemas like `scramSha256`, `scramSha512` and `gssapi`.
- render `name` and `summary` from `message.examples` field.
Part of https://github.com/asyncapi/spec/issues/536
=> feat: support for 2.1.0 version of spec

library/package-lock.json, library/package.json, playground/package-lock.json, playground/src/specs/streetlights.ts, web-component/package-lock.json
- Update `openapi-sampler` to `1.1.0` to fix the https://github.com/asyncapi/html-template/issues/195 issue
- Update the `streetlight` example
Generated example from provided schema in mentioned issue:
Fixes https://github.com/asyncapi/html-template/issues/195
=> fix: update openapi-sampler to 1.1.0

.sonarcloud.properties, library/src/components/Bindings.tsx, library/src/components/Schema.tsx, library/src/containers/Messages/Message.tsx, library/src/containers/Operations/Operation.tsx, library/src/containers/Servers/Server.tsx, playground/package-lock.json, web-component/package-lock.json
Render binding information as single component: in capsule instead of drop down.
Example:
Resolves #414
=> feat: render binding in capsule instead of drop down

library/src/helpers/parser.ts
- When I was compiling locally, I got a error, and this commit fixed this error.
=> refactor: added type assertion on handleError

library/package-lock.json, library/package.json, library/src/components/__tests__/Schema.test.tsx
- Bump parser-js dep to `1.12.0`
- Add test for checking new handling of circular references
> `next` branch isn't linked to the automatic bumps, so we need to bump it manually
Rendering of circular refs:
```yaml
components:
messages:
testMessage:
contentType: application/json
payload:
$ref: '#/components/schemas/NormalSchemaA'
schemas:
RecursiveSelf:
type: object
properties:
selfChildren:
type: array
items:
$ref: '#/components/schemas/RecursiveSelf'
selfObjectChildren:
type: object
properties:
test:
$ref: '#/components/schemas/RecursiveSelf'
nonRecursive:
type: string
selfSomething:
type: object
properties:
test: 
$ref: '#/components/schemas/RecursiveAncestor'
RecursiveAncestor:
type: object
properties:
ancestorChildren:
type: array …
```
=> fix: bump parser-js dep to 1.12.0

library/src/containers/AsyncApi/Layout.tsx, library/src/containers/Operations/Operation.tsx, library/src/containers/Servers/ServerSecurity.tsx, library/src/helpers/schema.ts
Improve performance of `resizeObserver`:
- move changing logic of `className`  to the observer.
- use `requestAnimationFrame`
- fix sonar complixity errors
Fixes: #498
=> fix: improve performance of resizeObserver

.gitpod.yml, README.md, docs/development/guide.md
-  Added `.gitpod.yml`
- Updated `README.md` with gitpod setup
- Updated `guide.md`
=> docs: added gitpod support

tsconfig.base.json
Add to every source map `sourcesContent` field with injected ts source code.
Resolves #504
=> fix: add inline sources in source maps

library/package.json, library/src/helpers/marked.ts
-  Updated marked and @type/marked patch in `library/package.json`.
-  Modified `marked.ts` import statement.
Fixes: #521
=> fix: updated marked patch

library/src/helpers/schema.ts
**IMPORTANT**: Currently marked as draft, as https://github.com/asyncapi/parser-js/pull/450 needs to be merged first.
Updating the Schema import, as the parser exports the Schema now in the root package, thus the types
can be used properly.
- none
=> fix: use typed Schema export

library/package-lock.json, library/package.json
Support 2.3.0 version of spec - bump `@asyncapi/parser` to the `1.14.0` version.
Part of https://github.com/asyncapi/spec/pull/681
=> feat: support 2.3.0 version of spec

library/package-lock.json, package-lock.json, playground/package-lock.json, web-component/package-lock.json
- Update dependencies in package-lock files
Fixes #567
=> fix: bump dependencies in package-lock files

package-lock.json, web-component/package-lock.json
Update dependencies in component and web-component.
Resolves #561 
Resolves #546
=> fix: update dependencies in component and web-component

library/package-lock.json, library/package.json
As in description.
Part of #577
=> fix: bump dependencies

docs/usage/standalone-bundle.md
- Fixing a broken link on documentation
=> docs: fixing broken link

library/package-lock.json, library/package.json, library/src/containers/Messages/Message.tsx, library/src/containers/Operations/Operation.tsx, library/src/containers/Servers/Security.tsx, library/src/containers/Servers/Server.tsx, playground/src/specs/streetlights.ts
- Render `messageId`:
- Render operation's `security`:
Part of https://github.com/asyncapi/spec/issues/735
=> feat: support AsyncAPI 2.4.0

.asyncapi-tool
The `.asyncapi-tool` file is corrected according to the errors made while validating with the [schema](https://github.com/asyncapi/website/blob/master/scripts/tools/tools-schema.json).
=> chore: asyncapi-tool fixes

library/package-lock.json, library/package.json, library/src/components/CollapseButton.tsx, playground/package-lock.json, web-component/package-lock.json
by inlining the HiChevronRight SVG
- remove react-icons dependency in favor of a single static SVG.
Addresses comment in https://github.com/asyncapi/asyncapi-react/issues/690#issuecomment-1398179446.
=> chore: remove react-icons dependency

library/package-lock.json, library/package.json, playground/src/specs/streetlights.ts
Support AsyncAPI `2.6.0`.
cc @derberg 
Part of https://github.com/asyncapi/spec/issues/894#issuecomment-1413412416
=> feat: support AsyncAPI 2.6.0

library/package-lock.json, library/package.json, library/src/helpers/parser.ts
=> feat: add protobuf payload support

library/src/__tests__/index.test.tsx, library/src/containers/Sidebar/Sidebar.tsx
The sidebar changes were not being tested anywhere, and hence the problems were not caught until I tried using them in https://github.com/asyncapi/html-template/pull/448.
This PR fixes those problems and adds a test to ensure that all shown options work.
=> fix: sidebar problems

library/package-lock.json, library/package.json
This PR updates the parser dependency as it contains an important fix that means we cannot properly use it in studio:  https://github.com/asyncapi/studio/pull/797
=> fix: update parser dependency

library/src/containers/AsyncApi/Standalone.tsx
Removes redundant jump statement 
Fixes #777
=> refactor: remove redudant return statement

library/src/containers/Operations/Operation.tsx
Fix for issue: #855
As reply channel was the request channel be displayed. This was fixed.
=> fix: reply channel displayed correctly

playground/package.json
- `.nojekyll` is needed for GitHub Pages: https://github.com/vercel/next.js/discussions/33751
=> fix: add dot nojekyll in playground to fix github pages

library/package.json, package-lock.json, web-component/package.json
updating one dependency because of security issues with old version
fixing package-lock as well
=> fix: bump  `isomorphic-dompurify` and fix `package-lock.json`

CODEOWNERS
This PR introduces me as one of the codeowners.
=> docs: add Ace as codeowner

playground/components/Tab.tsx
Fixed the navigation problem in NavBar.
fixes: #1008 
[Screencast from 16-09-24 09_25_04 PM IST.webm](https://github.com/user-attachments/assets/6236f148-d9b3-4173-9d43-253aa86f86a1)
=> fix: changed the Navigation tab functionality

playground/specs/dummy.ts
changed dommy to dummy in dummy.ts file.
=> fix: changed dommy to dummy

library/src/containers/AsyncApi/Layout.tsx
changed the breaking point from `1280` (xl in tailwind) to `1536` (2xl in tailwind)
BEFORE:
AFTER:
#954
#906
=> fix: breakpoint changed from 1280 to 1536
