asyncapi/asyncapi-react

CONTRIBUTING.md

Added information on the requirement to follow content guidelines from the `kyma-project` organization when adding text/screenshots/diagrams to the `asyncapi-react` repository.

Add info on contributing content

---

library/package-lock.json
library/src/containers/Schemas/Schema.tsx
library/src/helpers/beautifier.ts

- check if properties are objects and valid 
-  check for schema type  === 'object'
#67 #69

type checking if schema property is not string

---

.github/workflows/release.yml
library/package-lock.json
library/package.json
package-lock.json
package.json

- release pipeline fails atm because, during release, npm by default runs `npm run prepare` (default npm behavior) but this is done in release from `library` dir and fail, it should run from the root. I changed setup to run all from the root, except of the playground, unless you think that I should also make sure proper script for building playground is also on the root?

fix: adjust release configuration

---

playground/package.json

Without this PR playground relative links are pointing to the root `<script src="/static/js/main.2b18fd69.chunk.js">`. Adding homepage makes generated links look like `<script src="/asyncapi-react/static/js/main.2b18fd69.chunk.js">`. It is all because link to GH page is with specific path, repo name: https://asyncapi.github.io/asyncapi-react

fix: fix relative links generation for github pages

---

library/src/containers/Schemas/Schema.tsx
library/src/containers/Schemas/SchemaProperties.tsx
library/src/styles/fiori.css

This removes the usage of tables to describe schemas. Tables are a terrible way to display information with lots of optional fields, which is our case. Instead, I'm using a "fluent" layout similar to the one we use in the [HTML template](https://www.github.com/asyncapi/html-template).
Fixes #95

feat: Remove schema tables and use a fluent layout

---

library/src/components/Toggle.tsx

**Check for presence of `clickedItem`**
Otherwise it can result in `TypeError: clickedItem is undefined` as described in #107 
- check for `clickedItem` presence before accessing it
Fixes #107

fix: error complains clickedItem is undefined

---

library/src/helpers/beautifier.ts
library/src/styles/fiori.css

When `additionalProperties` is an object, it was handling it incorrectly. It's fixed now. Also, took the opportunity to fix the CSS horizontal overflow on the examples.

fix: additional properties handling

---

library/src/components/Toggle.tsx
library/src/constants.ts

Now, if user press any toggle, all the other toggles (in group - channels/messages etc) slide out. PR fixes this bug.

fix: wrong toggle state

---

library/src/styles/fiori.css

Remove CSS duplicate selectors in fiori.css.
Following the instructions found in issue 143 : 
- '**text-sm**'
- '**.asyncapi__markdown**'
-'.asyncapi__tag {... **font-weight: 300** ...}'
Bonus. Remove this as it is anyway overrided by this
Resolves #143

refactor: remove CSS duplicate selectors

---

library/src/helpers/beautifier.ts

We have some schemas that use nested fields and also array fields with markdown description. This was not correctly rendered before.
<details>
<summary>example-asyncapi.yaml</summary>
```yaml
asyncapi: 2.0.0
info:
title: Test Records
version: 0.21.1
channels:
our-records:
description: |
A short description of what we are doing.
subscribe:
description: |
**Important Information**
Important Information for this subscription
message:
oneOf:
- $ref: '#/components/messages/medicalAttendance'
components:
messages:
medicalAttendance:
name: medicalAttendance
title: Medical attendance records
summary: Create or update a single medical attendance record.
payload:
type: object
contentType: application/json
title: MedicalAttendance
description: |
*(Something in italics)* - Something …
```

fix: improve markdown rendering of nested fields

---

library/src/containers/Channels/Channel.tsx
library/src/containers/Channels/Operation.tsx
library/src/helpers/beautifier.ts
library/src/styles/fiori.css

Our schemas contain descriptions on the Channel and Operation level and it would be nice if we can have them displayed. The [HTML-renderer](https://playground.asyncapi.io/) includes them but they are missing in the react component.
I'm not sure if the representation and styling is ok. 
<details>
<summary>example-asyncapi.yaml</summary>
```yaml
asyncapi: 2.0.0
info:
title: Test Records
version: 0.21.1
channels:
our-records:
description: |
A short description of what we are doing.
subscribe:
description: |
**Important Information**
Important Information for this subscription
message:
oneOf:
- $ref: '#/components/messages/medicalAttendance'
components:
messages:
medicalAttendance:
name: medicalAttendance
title: Medical attendance records
summary: Create or update a single …
```

feat: display the description of channels and operations

---

library/src/containers/Schemas/SchemaProperties.tsx
library/src/styles/fiori.css

If we have a lot of enum values, the layout is broken because the enums are displayed in a single line. This can't be solved using CSS only, as there is no space between the enum values that the browser can break at. We add a spaced and remove the margin instead.
Before: 
After:

fix: let the list of enums break into multiple lines

---

library/src/helpers/__tests__/toKebabCase.test.ts
library/src/helpers/toKebabCase.ts

Remove unnecessary undefined on test
Fixes #141

test: remove unnecessary undefined on test

---

library/src/containers/Channels/Channel.tsx
library/src/containers/Messages/Message.tsx
library/src/containers/Messages/Messages.tsx
library/src/styles/fiori.css

If channel message is described by `oneOf` or `anyOf` component render message's index instead title/name. This PR change behaviour. If single message has title, then render title, if title doesn't exist, then check name of message, finally render index.
**Example**
Modified spec from https://github.com/asyncapi/asyncapi-react/issues/140
```yaml
asyncapi: 2.0.0
info:
title: Example project
version: 1.0.0
servers:
kafka:
url: kafka:29092
protocol: kafka
channels:
another-topic:
subscribe:
message:
oneOf:
- name: io.github.stavshamir.springwolf.example.dtos.ExamplePayloadDto
title: ExamplePayloadDto
payload:
"$ref": "#/components/schemas/ExamplePayloadDto"
- payload:
"$ref": "#/components/schemas/AnotherPayloadDto"
example-topic: …
```

feat: show title/name of message instead index in channel spec

---

playground/src/Playground.tsx
playground/src/common/defaultConfig.ts
playground/src/common/helpers.ts
playground/src/components/CodeEditorComponent.tsx
playground/src/components/styled.ts

- More info: https://github.com/asyncapi/asyncapi-react/issues/200
- Add `debounce` when user input new data in schema editor - after 750ms new view should be rendered with updated schema.
- Show refresh icon with spin animation when schema or config is updating.
> NOTE: `fix` is only added due to automatically push new playground.
New look:
Resolves #200

fix: refresh state in playground by debounce

---

playground/src/components/FetchSchema.tsx

**Addition of URL validation to the playground app**
- asyncapi-react playground app introduces error when clicking 'Fetch schema' button, if input field remains empty or contains improperly formed URL. This pull request adds validation of the URL address entered, with URL() constructor.
**Absense of URL validation in the playground app**

fix: URL validation in playground app

---

library/src/containers/Schemas/SchemaProperties.tsx
library/src/types.ts

According to [JSON Schema specification](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.1.3)
> 6.1.3. const
> The value of this keyword MAY be of any type, including null.
So it's made `any` in 'types.ts'.
And because `const: ` can be `any` including having a value of `null`, I cannot check for existence of property `const: ` with `typeof el.schema.content.const === null` or `typeof el.schema.content.const === undefined` - 'cause these might be simply regular values of `const` (like `const: null` or `const: undefined`) saying nothing about its very existence. So I had to use `el.schema.content.hasOwnProperty('const') === true` to check that such property even exists in the object.
Every type transforms well to `String` (functions also) except `object`, so …

fix: show 'const' values in property description (#210)

---

library/package-lock.json
library/package.json

- Update `merge` package from 1.2.1 to 2.1.0 to resolve WS-2020-0218 vulnerability.

fix: bump merge to 2.1.0

---

.github/workflows/if-nodejs-version-bump.yml

- bump workflow must install deps to generate assets
I'm not doing another fix or as this is obvious error in the workflow that we are fixing here

ci: bump workflow must install deps to generate assets

---

library/src/containers/Messages/Messages.tsx
library/src/containers/Messages/Payload.tsx
playground/src/Playground.tsx

Infer names for oneOf schemas and messages. 
Example schema:
```yaml
asyncapi: 2.0.0
info:
title: oneOf example 
version: 1.0.0-alpha
servers:
dev:
url: localhost:8080
protocol: ws
channels:
/stream:
description: the stream 
subscribe:
operationId: onStream
summary: stream of states info
message:
$ref: '#/components/messages/ResponseState'
bindings:
ws:
method: GET
components:
schemas:
ResponseState:
description: possible states of backend
oneOf:
- $ref: '#/components/schemas/SomeTypeName01'
- type: object
- $ref: '#/components/schemas/SomeTypeName03'
SomeTypeName01:
type: object
SomeTypeName02:
type: object
SomeTypeName03:
type: object  
messages:
ResponseState:
payload:
$ref: '#/components/schemas/ResponseState'
contentType: …
```

feat: infer names for oneOf schemas and messages

---

library/src/containers/AsyncApi/AsyncApi.tsx
library/src/containers/Channels/Channel.tsx
library/src/containers/Channels/Channels.tsx
library/src/containers/Channels/Operation.tsx
library/src/containers/Channels/Parameter.tsx
library/src/containers/Channels/Parameters.tsx
library/src/containers/Info/Info.tsx
library/src/containers/Info/License.tsx
library/src/containers/Messages/Message.tsx
library/src/containers/Messages/Messages.tsx
library/src/containers/Messages/Payload.tsx
library/src/containers/Schemas/Schemas.tsx
library/src/containers/Servers/Flow.tsx
library/src/containers/Servers/Flows.tsx
library/src/containers/Servers/Security.tsx
library/src/containers/Servers/SecurityItem.tsx
library/src/containers/Servers/Server.tsx
library/src/containers/Servers/Servers.tsx
library/src/containers/Servers/Variables.tsx
library/src/helpers/parser.ts
library/src/store/index.ts
library/src/store/useSpec.ts
library/src/types.ts
playground/src/Playground.tsx

> if someone think that the PR is too big, I will try to divide the PR into two smaller ones.
- Switch to `parser-js` in `Info`, `Servers` (also in single `Server`), `Channels` (also in single `Channel`), `Messages` (also in single `Message`), `Schemas` components,
- left single `Schema` component, because it is the most complicated component in package and it should be rewritten with https://github.com/asyncapi/shape-up-process/issues/87 task - also by this I left some code related to "beautify" our schema - if `Schema` component will be rewritten, we will remove about leftover 10-15% of code.
- I wanna treat PR as chore, because I wanna merge to `unify-component` branch :)
Part of …

refactor: switch to parser-js in most places 

---

package-lock.json
package.json
playground/src/Playground.tsx
playground/src/components/SplitWrapper.tsx
playground/src/components/index.ts
playground/src/components/styled.ts
playground/src/react-app-env.d.ts

- Added the ability to change the size of split panes
- Used a library called `react-split`
Fixes #268

feat: ability to change the size of the split panes

---

library/src/components/Markdown.tsx
library/src/components/Tag.tsx
library/src/components/Tags.tsx
library/src/components/index.ts
library/src/containers/AsyncApi/AsyncApi.tsx
library/src/containers/Channels/NewOperation.tsx
library/src/containers/Channels/NewOperations.tsx
library/src/containers/Messages/Messages.tsx
library/src/containers/Messages/NewMessage.tsx
library/src/containers/Messages/NewMessages.tsx
library/src/containers/Schemas/NewSchema.tsx
library/src/containers/Schemas/Schemas.tsx
library/src/helpers/schema.ts
playground/src/specs/streetlights.ts

Unify `Messages` and `Operations` components,
- styles as in previous PR with new `Schema` component is not related to this PR but to https://github.com/asyncapi/shape-up-process/issues/86 task,
- render `correlationId` and `tags` in messages and operations.
> **NOTE**: there are still `Servers` and `Info` to rewrite, as well as custom extensions and bindings. Then we can start styling :)
Examples:
Part of https://github.com/asyncapi/shape-up-process/issues/87

refactor: unify Messages and Operations components

---

library/src/containers/Bindings/Bindings.tsx
library/src/containers/Channels/NewOperation.tsx
library/src/containers/Extensions/Extensions.tsx
library/src/containers/Messages/NewMessage.tsx
library/src/containers/Schemas/NewSchema.tsx
library/src/containers/Servers/Server.tsx
library/src/helpers/schema.ts
playground/src/Playground.tsx
playground/src/specs/streetlights.ts

Unify bindings and extensions:
- as previous PRs, styles will be done in https://github.com/asyncapi/shape-up-process/issues/86
- render bindings and extensions as schema,
- render missed JSON-Schema (we don't also render them in HTML-template) like: `if/then/else`, `contains`, `propertyNames`, `patternProperties`, `not`. 
Examples:
Not:
Contains:
PropertyNames:
Part of https://github.com/asyncapi/shape-up-process/issues/87

refactor: unify bindings and extensions

---

.github/workflows/if-nodejs-version-bump.yml
.github/workflows/release-wc-and-playground.yml

As in title. Fix checkout to `next` branch in `wc-release` and `bump` workflows. Checkout to next when in `release_tag` will contain `next` substring.

ci: fix checkout to next branch

---

.github/workflows/bump.yaml
library/src/containers/Messages/Message.tsx
library/src/containers/Messages/MessageExample.tsx
library/src/containers/Operations/Operation.tsx
library/src/containers/Servers/Server.tsx
playground/src/index.tsx
playground/src/specs/streetlights.ts

- Check if given part of spec exists, if not, then don't return this part (changed parts are required to define in spec, but check it to be sure).
- Render first index of `oneOf` messages... `hasMultipleMessages` has broken meaning... 🤦🏼 
See also https://github.com/asyncapi/html-template/issues/191

fix: strictly check if a given part of spec exists and render single message from oneOf

---

.github/workflows/bump.yaml
library/src/components/Schema.tsx
library/src/helpers/__tests__/schema.test.ts
library/src/helpers/schema.ts
playground/src/components/styled.ts

Infer types in proper way:
- handle true/false schemas,
- infer types from keywords and from `enum`,
- handle empty schema,
- update `bump.yaml` workflow
Add missed tests for helpers (and also fix some bugs).

refactor: infer types in proper way and add tests

---

library/src/components/Schema.tsx
library/src/containers/Info/Info.tsx
library/src/containers/Messages/Message.tsx
library/src/containers/Operations/Operation.tsx
library/src/containers/Servers/Server.tsx
playground/src/specs/streetlights.ts

Render missed parts for operation:
- `operationId`
- `externalDocs`
Render `id` of spec.
ID:
Operation:
Part of https://github.com/asyncapi/asyncapi-react/issues/63

feat: render missed parts for operations and render spec id

---

library/package-lock.json
library/package.json

Update `openapi-sampler` package to `1.0.0`. Support for more type formats and JSON Schema 7 driven by support for OpenAPI 3.1.
Changes: https://github.com/Redocly/openapi-sampler/pull/122
Displaying `time` format:
Part of https://github.com/asyncapi/asyncapi-react/issues/209

feat: update openapi-sampler to 1.0.0 for better examples generation

---

library/src/components/Schema.tsx
playground/src/common/defaultConfig.ts

Rendering the circular items.
Fixes https://github.com/asyncapi/asyncapi-react/issues/351

fix: rendering the circular items

---

library/package-lock.json
library/package.json

As in title due to issue in marked.js library. More info is here https://github.com/markedjs/marked/issues/2106
See more https://github.com/markedjs/marked/issues/2106
See more https://github.com/asyncapi/html-template/issues/214

fix: decrease the marked.js version to 2.0.7

---

library/src/containers/Operations/Operation.tsx
playground/src/specs/streetlights.ts

- enable rendering of extensions on channel item object
- change order of rendering where channel is first before operation as channel is a higher level object
- extended dummy https://github.com/asyncapi/generator/pull/613

feat: enable rendering of extensions on channel level

---

README.md
docs/README.md
docs/usage/angular.md
docs/usage/standalone-bundle.md
docs/usage/web-component.md

As in title:
- document the Standalone bundle usage
Related issue:
Resolves https://github.com/asyncapi/asyncapi-react/issues/394

docs: add doc for Standalone Bundle

---

library/src/containers/Messages/Messages.tsx
library/src/containers/Schemas/Schemas.tsx
library/src/containers/Sidebar/Sidebar.tsx

Show only schemas and messages from components, not as currently, all schemas and messages.
Resolves https://github.com/asyncapi/html-template/issues/239

fix: show only schemas and messages from components

---

library/src/components/Markdown.tsx
library/src/components/Schema.tsx
library/src/containers/Messages/Message.tsx
library/src/containers/Messages/Messages.tsx
library/src/containers/Sidebar/Sidebar.tsx
library/src/styles/default.css

- Point to appropriate message in sidebar - use message name, not message uid,
- Fix href in the sidebar navigation for the `schemas`
- Render the `uid` from message as message's name in the sidebar
- Break long string content in the message's examples and schema's examples

fix: point to appropriate message in sidebar

---

library/package.json
package.json

- Make `styles/*` excluded from webpack tree shaking using `sideEffects` in `package.json`
When imported the styles should cause side effects, but because the current release (I am using `1.0.0-next.15`) has `"sideEffects": false,` in `package.json`, webpack tree shakes the `import '@asyncapi/react-component/styles/default.css';` at build time.
A workaround for us it's using `require` instead of `import` just for this specific file but I rather fix the root issue than mixing require/import. 
I have tested locally and works as expected. I am open to different approaches if you thought of one, but according to webpack docs, `sideEffects` should be used exactly for this situation, let me know your thoughts!

fix: add styles to sideEffects

---

library/src/containers/Operations/Operation.tsx

More info https://github.com/asyncapi/html-template/issues/264
Make fallback for new in `2.2.0` AsyncAPI version `channel.servers' field - support case when someone will use newest component with old generator, which isn't support `2.2.0` version of AsyncAPI.
Fixes https://github.com/asyncapi/html-template/issues/264

fix: make fallback for 2.2.0 channel.servers field

---

library/src/components/Bindings.tsx
library/src/components/Extensions.tsx
library/src/components/__tests__/Bindings.test.tsx
library/src/components/__tests__/Extensions.test.tsx
library/src/helpers/__tests__/schema.test.ts
library/src/helpers/schema.ts
playground/src/specs/streetlights.ts

Render empty extensions and bindings:
- improve `jsonFieldToSchema` function to handle `null` and `undefined` values.
- add unit tests for helper and also for `Bindings` and `Extensions` component
Resolves https://github.com/asyncapi/studio/issues/221

fix: render empty extensions and bindings

---

README.md

- add documentation on how to apply custom CSS styling
- add documentation on how to show a custom logo
#530

docs: add custom styling & custom logo

---

library/src/components/Schema.tsx

fix: remove lowercase in pattern

---

library/src/helpers/__tests__/schema.test.ts
library/src/helpers/schema.ts

Check if channel parameter's `schema` is null/undefined and then use fallback for that values. Add unit tests for fix.
See https://github.com/asyncapi/studio/issues/309
See https://github.com/asyncapi/studio/discussions/326

fix: add fallback for null parameter's schema

---

library/package.json

We use `react` and `react-dom` in component, but we don't have defined these packages as peer-dependencies and e.g. yarn throw error due to this fact. See more #609 
I tested package installing new project with yarn without and with `react/react-dom` deps and yarn in first case throw errors, in second installation passed.
Resolves #609

fix: define react and react-dom as peerDependencies

---

library/package-lock.json
library/package.json
library/src/components/CollapseButton.tsx
library/src/components/Schema.tsx
library/src/containers/Messages/MessageExample.tsx

Add collapse button for nested subschemas in the Schema component:
Fix `uid` for array schemas (wrong uid appears in some cases).
Resolves #440
Resolves #605 
Gitpod url (you need to login by github accout): https://gitpod.io/#https://github.com/asyncapi/asyncapi-react/pull/620, wait for installing deps and open `3000` port (you should see notification for that).
cc @mcturco @derberg

feat: add deep collapse button in schema component

---

README.md
docs/usage/angular.md
docs/usage/nextjs.md
docs/usage/standalone-bundle.md
docs/usage/vue.md
docs/usage/web-component.md

I was using the original command npm install --save @asyncapi/react-component when doing research for my article and I had some issues which were resolved but only when I requested senior dev to look at it.
It is more likely due to my inexperience but there are other junior developers like myself who may not know to use npm install --save @asyncapi/react-component@next command.
To make juniors life easier, may I ask to merge this request into your branch?
Thank you.

docs: update the command to install the component

---

docs/configuration/config-modification.md
library/src/config/config.ts
library/src/config/default.ts
library/src/constants.ts
library/src/containers/Operations/Operation.tsx
library/src/containers/Sidebar/Sidebar.tsx
package.json

Updated documentation. All tests pass. Not sure how I would go about adding new tests for this feature...
- Provide two new config properties for overriding the default "PUB" and "SUB" operation label text.
**Reason for feature**
At my company, Megh Computing Inc, we are using AsyncAPI to document our WebSocket API. Our API does not operate in a typical PUB-SUB way; clients do not "publish" data to the endpoints. Any data sent to an endpoint is to configure that WebSocket session and specify the async events that the client wishes to receive. We have received feedback from our customers that the terminology label "PUB" is confusing. Our solution is to rename the "PUB" label to "CONF", but the tool currently does not support overriding …

feat: add config options to override pub sub label text

---

library/src/components/Schema.tsx
library/src/components/__tests__/Schema.test.tsx
library/src/helpers/__tests__/schema.test.ts
library/src/helpers/schema.ts

- Render `default` and `const` boolean values in Schema component.
- Add unit test
cc @derberg @andres-JT 
Fixes #634

fix: render default,const boolean values in Schema component

---

library/package-lock.json
library/package.json
library/src/containers/Servers/Server.tsx
playground/src/specs/streetlights.ts

Support AsyncAPI 2.5.0:
- render tags in Server Object
Part of https://github.com/asyncapi/spec/issues/830

feat: support AsyncAPI 2.5.0

---

library/src/components/Schema.tsx
library/src/styles/default.css

- Change schema name style word breaking to use [`overflow-wrap: anywhere`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap#anywhere) to prevent content going under the sidebar when using long schema names that cannot be broken up into words.
**Why is this an issue?**
When using long names for schemas that cannot be broken up into words like when using Java package names, the content can go under the sidebar.
This makes the content unreadable to a large extent unless the window is made small enough for the sidebar to be put inside the burger menu.
When applying `overflow-wrap: anywhere` the browser will still try to wrap on words but also allows breaking up long, otherwise unbreakable strings to avoid overflowing. …

fix: change schema name word breaking to anywhere

---

.releaserc

Release of 1.0 failed -> https://github.com/asyncapi/asyncapi-react/actions/runs/6322951494
We can use global generic release workflow, but not the config, cause of monorepo. 
`get-global-releaserc` topic already removed

ci: eject from global release config file

---

playground/package-lock.json

even though https://github.com/asyncapi/asyncapi-react/pull/775 was fine, there were still some issue with package lock
```lerna notice cli v3.22.1
lerna info ci enabled
lerna info Bootstrapping 3 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 1 in 'playground'
lerna ERR! npm ci stderr:
npm verb cli /opt/hostedtoolcache/node/16.20.2/x64/bin/node /opt/hostedtoolcache/node/16.20.2/x64/bin/npm
...
npm verb stack `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```
ref: https://github.com/asyncapi/asyncapi-react/actions/runs/6378857264/job/17310505632?pr=791

fix: sync package and package-lock

---

library/src/styles/default.css

- Removed some unexpected empty blocks from the path library/src/styles/default.css
fixes #787

refactor: remove the unexpected empty blocks

---

library/src/containers/Servers/Security.tsx

Adds an operational chain instead of an expression check
Fixes #780

refactor: add an operational chain instead of expressions check

---

library/src/containers/Servers/Security.tsx

- Removed the expressions and added optional chain expression 
resolve #781

refactor: add optional chain expression

---

library/src/helpers/message.ts

- Added optional chain expressions
resolves #782

refactor: add optional chain expressions

---

library/src/helpers/message.ts

-Removed the redundant jump code
#785

refactor: remove the redundant-jump code

---

library/src/helpers/server.ts

- When using nested if statements, it can be difficult to keep track of the logic and understand the flow of the code. Using else if makes the code more concise and easier to follow.
#786

refactor: improve if-else code in `server.ts`

---

CONTRIBUTING.md
web-component/package-lock.json
web-component/package.json
web-component/webpack.config.js

- Add missing NodeJS polyfills
- Fix links to the development guide in CONTRIBUTING.md
Resolves #813

fix: missing nodejs polyfills for web-component

---

library/src/components/Schema.tsx
library/src/helpers/schema.ts
playground/src/specs/streetlights.ts

Applicators can be a little hard to navigate, especially on deeply nested schema. While the `uid` provides a nice middle-ground solution, it doesn't actually work when schemas are defined outside of the main specification and more importantly, it isn't necessarily meant to be human-readable. The `title` property however is meant just for that.
- This PR does just that, it adds the `title` next to branches enumeration in `{one,any,all}Of` applicators. When not available, it defaults to the current behavior.
N/A

feat: use schema's title when available in `{one,any,all}Of` applicators

---

.gitignore
library/src/helpers/__tests__/__snapshots__/schema.test.ts.snap
library/src/helpers/__tests__/schema.test.ts
library/src/helpers/schema.ts

- Fix for https://github.com/asyncapi/asyncapi-react/pull/744#discussion_r1433826404
Fixes bug introduced in #744

fix: render schema title if it exists

---

library/src/helpers/__tests__/schema.test.ts
library/src/helpers/schema.ts

- If a schema of type "object" is used, it is hard to guess the real type in complex big schemas
- Append the title of object make thinks easy to understand.
Visualization of change

feat: append schema title to objects

---

playground/next.config.mjs

- fixes playground when deployed to github pages
Fixes #929

fix: fixes playground when deployed to github pages

---

library/package.json
library/src/components/Href.tsx
library/src/components/Markdown.tsx
library/src/containers/Servers/Security.tsx
library/src/containers/Sidebar/Sidebar.tsx
library/src/standalone-codebase.ts
package-lock.json
package.json
playground/app/page.tsx
web-component/package.json

- upgrades react to v18 by following https://legacy.reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html
See also #891

feat!: upgrade to react v18

---

.github/workflows/release-wc-and-playground.yml
playground/app/page.tsx
playground/components/CodeEditorComponent.tsx
playground/components/SplitWrapper.tsx
web-component/package.json
web-component/webpack.config.js

webcomponent and playground releases were failing
https://github.com/asyncapi/asyncapi-react/actions/runs/9496432356/job/26170818500
I also added now slack notifications for failing releases as we had no idea and nobody explicitly wrote to us about it
I learned from https://github.com/asyncapi/asyncapi-react/pull/1016#issuecomment-2186453509

fix: remove code needed prior react 18 to fix release of webcomponent

---

web-component/bump-react-comp.sh

Looks like depending on npm versions there are different behaviours of installation
even though existing script has explicit `--save`, if some other script in the same run updated dependency to lates, and it is already in node_modules, installation of the same dependency with `--save` in another project in monorepo, will not result in updates in package.json
This this PR introduce initial remove of dependency and then fresh installation

fix: update web-component bumping script for react

---

docs/configuration/config-modification.md
library/src/config/config.ts
library/src/config/default.ts
library/src/containers/Messages/Messages.tsx

- Adds a configuration `show.messageExamples`, which when `true` also shows examples for the messages in the `Messages` section (and not only for the messages in the "Operations" section).
**Background:**
Maybe we are using the AsyncAPI CLI not in the intended way. But we have messages that are not referenced in one of the operations, so that the examples for these messages are not visible. This PR is proposing to add a new configuration, which will show examples for the messages listed in the "Messages" section.

feat: add configuration to always show message examples

---

docs/configuration/config-modification.md
library/src/config/config.ts
library/src/containers/Sidebar/Sidebar.tsx
library/src/containers/Sidebar/__tests__/SideBar.test.tsx

- Adds a configuration `useChannelAddressAsIdentifier` to the sidebar configuration, so that the channel address is used as a fallback also for AsyncAPI v3 documents. This helps maintain consistent UI when migrating from V2 to V3.
Fixes https://github.com/asyncapi/asyncapi-react/issues/1018

feat: add configuration to use channel addresses in the sidebar for AsyncAPI v3

---

library/package.json
package-lock.json

- Remove @types/highlight.js, because highlight.js have own type definitions
- Update isomorphic-dompurify and @types/dompurify

fix: update isomorphic-dompurify and remove @types/highlight.js

---

library/package.json
library/src/containers/AsyncApi/Standalone.tsx
library/src/containers/Error/Error.tsx
library/src/helpers/parser.ts
package-lock.json

Diagnostics with severity 0 are displayed as errors.
Before 
(Invalid document 👇 with syntax error)
After
(Invalid document 👇 with syntax error)
(document with spec specific errors 👇)
**Related Issue**
#1048 
#874

fix: informative Stubs when document is invalid

---

library/src/helpers/parser.ts

Improved the error handling in `helpers/parser` to convert diagnostics of severity 0 into errors which can be displayed.
This pr is almost same to #1068. It just targets different kind of parsing. ie `parseFromUrl` method which is used when inside of  vs-asyncapi-preview extension.
These are the following changes it does to the vs-asyncapi-preview extension.
Before
After
#1077 
and
[https://github.com/asyncapi/vs-asyncapi-preview/issues/200](https://github.com/asyncapi/vs-asyncapi-preview/issues/200)

feat: fix of make @asyncapi/react component with vs asyncapi preview

---

library/src/containers/Messages/Message.tsx

fixes #1049
- Removed redundant MessageId from Message.tsx
Before:
After:

fix: removed redundant MessageId

---

playground/specs/dummy.ts
playground/specs/streetlights.ts

Changed oparation to operation in dummy.ts and streetlights.ts.

docs: corrected typo error

---

library/src/components/Href.tsx

Now the external link will open in the same window.
#962 
[video](https://www.loom.com/share/a4d6280fb6564479b6204c12c0fcf2ea?sid=5f0cc668-4335-431d-966e-4d6b7a2ccee2)

fix: external link will open in the same window

---

library/src/containers/Operations/Operation.tsx

Fixed the issue by using window.location.pathname in the href attribute, so that full URL (current path + fragment) is generated when clicking on server links.
Fixes #1097

fix: fragment navigation issue fix

---

library/src/components/Schema.tsx
library/src/containers/Messages/Message.tsx
library/src/containers/Messages/MessageExample.tsx
library/src/containers/Operations/Operation.tsx

This PR is related to the issue with inconsistent styling. According to the issue, "WCAG 2.0 guideline 3.2.4 Consistent Identification states "Components that have the same functionality within a set of Web pages are identified consistently". 
For example:
If we move to [async-react website](https://asyncapi.github.io/asyncapi-react/),
We will notice that there are multiple elements with a solid color background, but only some of them are a button.
To resolve this, the ask in the issue was:
1. Buttons to be styled with rectangular outline.
2. Tags to be styled with solid background.
In this PR, changes have been made in 4 files:
1. **In "library/src/components/Schema.tsx" file:**
Addresses the tags "Default values", "const", "Allowed …

refactor: added consistent styling for buttons and tags

---

library/src/containers/Sidebar/Sidebar.tsx

fixed this issue #1109 
Description
The anchor link for a message in the sidebar does not work as expected when message.name() and message.id() differ.
Expected result
Clicking on a message in the sidebar should set the correct hash in the URL and scroll the message into view.
Actual result
The anchor link only works if message.name() and message.id() are identical.
If message.name() is not provided, the hash becomes #message-undefined.
before
after
Code changes required :

fix(sidebar): resolved sidebar hash URL navigation issue
